# Generated by Django 4.0.5 on 2022-06-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personas',
            new_name='Integrantes',
        ),
    ]
